/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{
    collapsed: false,
    type: 'category',
    label: 'Getting Started',
    items: ['intro/intro', 'tutorial-basics/create-a-document'],
  },{
    collapsed: false,
    type: 'category',
    label: 'Developing',
    items: ['tutorial-basics/create-a-blog-post'],
  },{
    collapsed: false,
    type: 'category',
    label: 'API',
    items: ['tutorial-basics/create-a-page'],
  },{
    collapsed: false,
    type: 'category',
    label: 'Getting Started',
    items: ['intro/intro', 'tutorial-basics/create-a-document'],
  },{
    collapsed: false,
    type: 'category',
    label: 'Developing',
    items: ['tutorial-basics/create-a-blog-post'],
  },{
    collapsed: false,
    type: 'category',
    label: 'API',
    items: ['tutorial-basics/create-a-page'],
  },{
    collapsed: false,
    type: 'category',
    label: 'Getting Started',
    items: ['intro/intro', 'tutorial-basics/create-a-document'],
  },{
    collapsed: false,
    type: 'category',
    label: 'Developing',
    items: ['tutorial-basics/create-a-blog-post'],
  },{
    collapsed: false,
    type: 'category',
    label: 'API',
    items: ['tutorial-basics/create-a-page'],
  },{
    collapsed: false,
    type: 'category',
    label: 'Getting Started',
    items: ['intro/intro', 'tutorial-basics/create-a-document'],
  },{
    collapsed: false,
    type: 'category',
    label: 'Developing',
    items: ['tutorial-basics/create-a-blog-post'],
  },{
    collapsed: false,
    type: 'category',
    label: 'API',
    items: ['tutorial-basics/create-a-page'],
  }
],

  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
